### PR TITLE
Improved version of Detail View

### PR DESCRIPTION
**Pull request by ferion11**
For the https://github.com/rodlie/qtfm/issues/135
I'm using this on my notebook.

### CODE REVIEW

**Comment by rodlie** [comment]
Thanks, I will review the changes tomorrow.

**Comment by rodlie** [comment]
Sorry for the late reply. Looks ok, but files should not have the expand icon.
qtfm-detailview-bug

**Comment by ferion11** [comment]
On the View the files don't have expand icon. If you use the "QFileSystemModel", the expand icon show only for directory. But the "myModel" (from libfm) is saying that the file item can be expanded. I thought it was a feature, such as for previewing files or opening compressed files as if they were directories. I will review the "myModel" (from libfm) code.

**Comment by rodlie** [comment]
ahh, yes. Then we have a bug in mymodel.

**Comment by rodlie** [comment]
fixed in master.

**Comment by rodlie** [comment]
But that broke the tree dock... Will look into that later.

**Comment by ferion11** [comment]
Probably because directories aren't the only ones having children. Some like this should solve:
if (!parent.isValid()) return true; // for drives

**Comment by rodlie** [comment]
Seems to work, thanks.

**Pull request merged**
